version: '3.8'
services:
  vproddb:
    build:
      context: ./Docker-files/db
      image: vprocontainers/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - ENV MYSQL_ROOT_PASSWORD=vprodbpass


  vprocache01:
    image: memcached
    ports:
      - 11211:11211

      
  vpromq01:
    image: rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  vproapp:
    build:
      context: ./Docker-files/app
      image: vprocontainers/vprofileapp
      container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vprweb:
    build:
      context: ./Docker-files/web
      image: vprocontainers/vprofileapp
      container_name: vproweb
    ports:
      - "80:80"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
      
volumes:
  vprodbdata: {}
  vproappdata: {}     